# Generated by Django 3.2.5 on 2022-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
